TRUNCATE TABLE `#__community_users`;;
INSERT INTO `#__community_users` (`userid`, `status`, `points`, `posted_on`, `avatar`, `thumb`, `invite`, `params`, `view`, `friendcount`, `alias`, `latitude`, `longitude`) VALUES
(62, '', 12, '0000-00-00 00:00:00', 'components/com_community/assets/default.jpg', 'components/com_community/assets/default_thumb.jpg', 0, 'notifyEmailSystem=1\nprivacyProfileView=0\nprivacyPhotoView=0\nprivacyFriendsView=0\nprivacyVideoView=1\nnotifyEmailMessage=1\nnotifyEmailApps=1\nnotifyWallComment=0\n\n', 0, 0, '', 255, 255),
(83, '', 2, '0000-00-00 00:00:00', 'components/com_community/assets/group.jpg', 'components/com_community/assets/group_thumb.jpg', 0, 'notifyEmailSystem=1\nprivacyProfileView=10\nprivacyPhotoView=0\nprivacyFriendsView=0\nprivacyVideoView=1\nnotifyEmailMessage=1\nnotifyEmailApps=1\nnotifyWallComment=0\nprofileVideo=11\n\n', 4, 0, '', 255, 255),
(84, '', 2, '0000-00-00 00:00:00', 'components/com_community/assets/default.jpg', 'components/com_community/assets/default_thumb.jpg', 0, 'notifyEmailSystem=1\nprivacyProfileView=20\nprivacyPhotoView=0\nprivacyFriendsView=0\nprivacyVideoView=1\nnotifyEmailMessage=1\nnotifyEmailApps=1\nnotifyWallComment=0\nprofileVideo=12\n\n', 4, 0, '', 255, 255),
(85, '', 2, '0000-00-00 00:00:00', 'components/com_community/assets/default.jpg', 'components/com_community/assets/default_thumb.jpg', 0, 'notifyEmailSystem=1\nprivacyProfileView=10\nprivacyPhotoView=0\nprivacyFriendsView=0\nprivacyVideoView=1\nnotifyEmailMessage=1\nnotifyEmailApps=1\nnotifyWallComment=0\n\n', 0, 0, '', 255, 255),
(86, '', 2, '0000-00-00 00:00:00', 'components/com_community/assets/group.jpg', 'components/com_community/assets/group_thumb.jpg', 0, 'notifyEmailSystem=1\nprivacyProfileView=10\nprivacyPhotoView=0\nprivacyFriendsView=0\nprivacyVideoView=1\nnotifyEmailMessage=1\nnotifyEmailApps=1\nnotifyWallComment=0\n\n', 2, 0, '', 255, 255),
(87, '', 2, '0000-00-00 00:00:00', 'components/com_community/assets/default.jpg', 'components/com_community/assets/default_thumb.jpg', 0, 'notifyEmailSystem=1\nprivacyProfileView=20\nprivacyPhotoView=0\nprivacyFriendsView=0\nprivacyVideoView=1\nnotifyEmailMessage=1\nnotifyEmailApps=1\nnotifyWallComment=0\nprofileVideo=3\n\n', 0, 0, '', 255, 255),
(79, '', 2, '0000-00-00 00:00:00', 'components/com_community/assets/default.jpg', 'components/com_community/assets/default_thumb.jpg', 0, 'notifyEmailSystem=1\nprivacyProfileView=10\nprivacyPhotoView=0\nprivacyFriendsView=0\nprivacyVideoView=1\nnotifyEmailMessage=1\nnotifyEmailApps=1\nnotifyWallComment=0\nprofileVideo=0\n\n', 0, 0, '', 255, 255),
(80, '', 2, '0000-00-00 00:00:00', 'components/com_community/assets/group.jpg', 'components/com_community/assets/group_thumb.jpg', 0, 'notifyEmailSystem=1\nprivacyProfileView=30\nprivacyPhotoView=0\nprivacyFriendsView=0\nprivacyVideoView=1\nnotifyEmailMessage=1\nnotifyEmailApps=1\nnotifyWallComment=0\n\n', 0, 0, '', 255, 255),
(81, '', 2, '0000-00-00 00:00:00', 'components/com_community/assets/default.jpg', 'components/com_community/assets/default_thumb.jpg', 0, 'notifyEmailSystem=1\nprivacyProfileView=20\nprivacyPhotoView=0\nprivacyFriendsView=0\nprivacyVideoView=1\nnotifyEmailMessage=1\nnotifyEmailApps=1\nnotifyWallComment=0\n\n', 0, 0, '', 255, 255),
(82, '', 2, '0000-00-00 00:00:00', 'components/com_community/assets/default.jpg', 'components/com_community/assets/default_thumb.jpg', 0, 'notifyEmailSystem=1\nprivacyProfileView=10\nprivacyPhotoView=0\nprivacyFriendsView=0\nprivacyVideoView=1\nnotifyEmailMessage=1\nnotifyEmailApps=1\nnotifyWallComment=0\nprofileVideo=2\n\n', 0, 0, '', 255, 255);;



TRUNCATE TABLE `#__xipt_profiletypes` ;;
INSERT INTO `#__xipt_profiletypes` (`id`, `name`, `ordering`, `published`, `tip`, `privacy`, `template`, `jusertype`, `avatar`, `approve`, `allowt`, `group`, `watermark`, `params`) VALUES
(1, 'PROFILETYPE-1', 2, 1, 'PROFILETYPE-ONE-TIP', 'public', 'default', 'Registered', 'components/com_community/assets/default.jpg', 0, 0, 1, '', ''),
(2, 'PROFILETYPE-2', 1, 1, 'PROFILETYPE-TWO-TIP', 'public', 'blueface', 'Editor', 'components/com_community/assets/group.jpg', 0, 0, 0, '', ''),
(3, 'PROFILETYPE-3', 3, 1, 'PROFILETYPE-THREE-TIP', 'members', 'blackout', 'Publisher', 'components/com_community/assets/default.jpg', 0, 0, 4, '', ''),
(4, 'PROFILETYPE-4', 4, 0, 'PROFILETYPE-THREE-TIP', 'members', 'blackout', 'Registered', 'components/com_community/assets/default.jpg', 0, 0, 0, '', '');;


TRUNCATE TABLE `#__xipt_aclrules`;;
INSERT INTO `#__xipt_aclrules` (`id`, `rulename`, `aclname`, `coreparams`, `aclparams`, `published`) VALUES
(2, 'access  profile video', 'accessprofilevideo', 'core_profiletype=1\ncore_display_message=PHA+WU9VIEFSRSBOT1QgQUxMT1dFRCBUTyBBQ0NFU1MgVEhJUyBSRVNPVVJDRTwvcD4=\nforce_to_redirect=0\ncore_redirect_url=index.php?option=com_community\n\n', 'other_profiletype=2\nacl_applicable_to_friend=0\n\n', 1),
(3, 'access  profile video', 'accessprofilevideo', 'core_profiletype=2\ncore_display_message=PHA+WU9VIEFSRSBOT1QgQUxMT1dFRCBUTyBBQ0NFU1MgVEhJUyBSRVNPVVJDRTwvcD4=\nforce_to_redirect=0\ncore_redirect_url=index.php?option=com_community\n\n', 'other_profiletype=3\nacl_applicable_to_friend=1\n\n', 1);;

TRUNCATE TABLE `#__community_videos`;;
INSERT INTO `#__community_videos` (`id`, `title`, `type`, `video_id`, `description`, `creator`, `creator_type`, `created`, `permissions`, `category_id`, `hits`, `published`, `featured`, `duration`, `status`, `thumb`, `path`, `groupid`, `filesize`, `storage`) VALUES
(1, 'Kites Song Fire |  Kites Fire  |  Hrithik Roshan Fire  |  Kites Song Promo  Fire  |  Fire |', 'youtube', 'PN626ZXD204', 'Kites Song Promo -  Fire  \r\nChoreographer - Flexy        Music - Rajesh Roshan\r\n\r\nKITES Releasing Worldwide on 21st May (2010)', 85, 'user', '2010-05-25 11:57:38', '0', 1, 5, 1, 0, 62, 'ready', 'images/videos/88/thumbs/BeYcKnpwhj9.jpg', 'http://www.youtube.com/watch?v=PN626ZXD204', 0, 0, 'file'),
(2, 'Top 10 Best Web Hosting Reviews - SCAMS EXPOSED', 'youtube', 'V8PidNJLrek', 'Are "HOST REVIEW" sites honest? Are they unbiased, impartial, and factual... or are they just after your money? How does a hosting company get on the "top 10" list? \r\n\r\nAmazingly most hosting reviews websites have one thing in common: They are getting paid by hosting companies for reviews (either directly in the form of advertising or indirectly via affiliate commissions) -- making their reviews extremely biased, one-sided, and highly questionable in terms of accuracy. They all promote the same group of companies. \r\n\r\nThe reason that the same hosting companies always make it to the "top" of the hosting comparison charts is because those companies, one way or another, pay to be listed there. These hosts include Host Monster, Blue Host, Lunar Pages, IX Webhosting, InMotionHosting, StartLogic, Host Pappa, Pow Web, etc. \r\n\r\nIt''s a well-known fact web hosting companies running their affiliate programs through Commission Junction offer among the highest affiliate commissions in the hosting industry. Thus "clever" PPC (pay per click) affiliate marketers decided: why not create websites with "top web hosting companies" lists and list these companies as "top"? \r\n\r\nHosting company reviews seldom base their "rating" on their quality of service (although many claim to). Instead, most of them rate a webhost on the *size* of the affiliate commission. Those web hosts offering the highest commissions usually get the top spots -- because those hosting companies pay the most money.\r\n\r\nSo the next time you''re looking for the best web hosting company (and you undoubtedly come across a "reviews" site), STOP AND THINK: What''s their true objective? Are they providing you with impartial, unprejudiced facts? Or are they simply selling you a bill of goods, deceptively packaged in a "Top-10" list bought and paid for in the Twilight Zone? Visit HOSTING-REVIEWS-EXPOSED.COM for more information.', 86, 'user', '2010-07-01 13:15:18', '0', 1, 6, 1, 0, 211, 'ready', 'images/videos/83/thumbs/wfrYZ4PD1D2.jpg', 'http://www.youtube.com/watch?v=V8PidNJLrek&feature=related', 0, 0, 'file'),
(3, 'Top 10 Best Web Hosting Reviews - SCAMS EXPOSED', 'youtube', 'luXxeIlOoKU', 'Hrithik Roshan, Dance, Kites, Hindi Movie, Watch Online, SominalTv, Kangana Ranawat, Fire, Full Song, Music Video', 87, 'user', '2010-05-25 12:28:01', '0', 1, 7, 1, 0, 189, 'ready', 'images/videos/90/thumbs/gQ1sAuG34du.jpg', 'http://www.youtube.com/watch?v=luXxeIlOoKU', 0, 0, 'file'),
(4, 'Build a Joomla Website', 'youtube', 'lGub1u8v8i8', 'http:www.buildajoomlawebsite.com\r\nIf you have ever wanted to build a Joomla website...you need to see this', 79, 'user', '2010-06-15 09:21:24', '0', 1, 1, 1, 0, 298, 'ready', 'images/videos/79/thumbs/O6iK9kZPqFt.jpg', 'http://www.youtube.com/watch?v=lGub1u8v8i8&feature=related', 0, 0, 'file'),
(5, 'Build easy websites using Joomla tutorials', 'youtube', 'fVr7huePbIA', 'Its a clip that shows you ways to build a website using joomla..a powerful open source...\r\n\r\nYou can create websites in 10 mins..that too with features and a database that supports..and gives you access to admin..enjoy!!\r\n\r\nfind more information from joomlasuccess.com', 80, 'user', '2010-06-15 09:23:09', '0', 1, 1, 1, 0, 15, 'ready', 'images/videos/80/thumbs/SsnDTqPD89x.jpg', 'http://www.youtube.com/watch?v=fVr7huePbIA&feature=related', 0, 0, 'file'),
(6, 'How to Build and Manage Your Own Website - (Joomla Editors)', 'youtube', 'ESEU8XqyrZE', 'http:www.MakeYourWebsite123.com\r\n\r\nEasily Edit, Design And Format Your Pages Using WYSIWYG Editor, Without Ever Messing With HTML And Other Programming Languages\r\nMake you own website\r\nmake a website\r\nhow to make a website\r\nhow to make your own website for free', 81, 'user', '2010-06-15 09:25:14', '0', 1, 1, 1, 0, 272, 'ready', 'images/videos/81/thumbs/rSG2g8pNIYc.jpg', 'http://www.youtube.com/watch?v=ESEU8XqyrZE&feature=related', 0, 0, 'file'),
(7, 'How to createmake your own website 4 free', 'youtube', 'qB6zTgMWcDA', 'this is how to create youre own website first: go to www.freeservers.com and then click the box with the free on the top. and then follow the steps and fill the blanks and in no time you have you''re website!\r\n\r\n AXLPOGI Productions-MADE IN PHILIPPINES', 95, 'user', '2010-06-15 10:11:53', '0', 1, 1, 1, 0, 226, 'ready', 'images/videos/95/thumbs/HW82lNd9oWo.jpg', 'http://www.youtube.com/watch?v=qB6zTgMWcDA&feature=related', 0, 0, 'file'),
(8, 'Make a free website!!', 'youtube', '8aaNngwsY3c', 'its cool free and fast!! great for gamers, for clans yada yada yada\r\nmy site: www.valenciascape.ucoz.com\r\nto register for a site:www.ucoz.com', 96, 'user', '2010-06-15 10:15:12', '0', 1, 1, 1, 0, 220, 'ready', 'images/videos/96/thumbs/BN4EaRT8955.jpg', 'http://www.youtube.com/watch?v=8aaNngwsY3c&feature=related', 0, 0, 'file'),
(9, 'Best Free Website Hosting: With FTP, PHP, and MySQL!', 'youtube', 'whPYvGuqviI', 'Free website hosting.\r\nhttp:www.podserver.info\r\nHost your own message board forum, blog, CMS, image gallery, Commerce, wiki, and more. Unlike other free hosting plans, this includes full access to FTP, PHP, MySQL, Apache and Control Panel.\r\n\r\nFree web hosting services:\r\n• 300 MB disk space\r\n• 10 GB monthly transfer\r\n• 7 MySQL databases\r\n• Free 247 tech support and instant activation\r\n• FTP, file manager, MySQL, Ion Cube, Zend Optimizer, and Apache\r\n• PHP with ''safe_mode'' off and GD enabled\r\n• Password protect directories\r\n• Control panel and Fantastico® like automatic script installer\r\n• 6 Addon domains, 6 parked domains, and 6 sub-domains\r\n• Webmail, sendmail and POP email\r\n• Quad Xeon grid servers with multiple fiber optic connections\r\n\r\nMusic: Kevin MacLeod', 97, 'user', '2010-06-15 10:20:07', '0', 1, 1, 1, 0, 32, 'ready', 'images/videos/97/thumbs/gNRmYbqgB33.jpg', 'http://www.youtube.com/watch?v=whPYvGuqviI&feature=related', 0, 0, 'file'),
(10, 'Top 10 Best Web Hosting Reviews - SCAMS EXPOSED', 'youtube', 'V8PidNJLrek', 'Are "HOST REVIEW" sites honest? Are they unbiased, impartial, and factual... or are they just after your money? How does a hosting company get on the "top 10" list? \r\n\r\nAmazingly most hosting reviews websites have one thing in common: They are getting paid by hosting companies for reviews (either directly in the form of advertising or indirectly via affiliate commissions) -- making their reviews extremely biased, one-sided, and highly questionable in terms of accuracy. They all promote the same group of companies. \r\n\r\nThe reason that the same hosting companies always make it to the "top" of the hosting comparison charts is because those companies, one way or another, pay to be listed there. These hosts include Host Monster, Blue Host, Lunar Pages, IX Webhosting, InMotionHosting, StartLogic, Host Pappa, Pow Web, etc. \r\n\r\nIt''s a well-known fact web hosting companies running their affiliate programs through Commission Junction offer among the highest affiliate commissions in the hosting industry. Thus "clever" PPC (pay per click) affiliate marketers decided: why not create websites with "top web hosting companies" lists and list these companies as "top"? \r\n\r\nHosting company reviews seldom base their "rating" on their quality of service (although many claim to). Instead, most of them rate a webhost on the *size* of the affiliate commission. Those web hosts offering the highest commissions usually get the top spots -- because those hosting companies pay the most money.\r\n\r\nSo the next time you''re looking for the best web hosting company (and you undoubtedly come across a "reviews" site), STOP AND THINK: What''s their true objective? Are they providing you with impartial, unprejudiced facts? Or are they simply selling you a bill of goods, deceptively packaged in a "Top-10" list bought and paid for in the Twilight Zone? Visit HOSTING-REVIEWS-EXPOSED.COM for more information.', 82, 'user', '2010-07-01 13:15:18', '0', 1, 6, 1, 0, 211, 'ready', 'images/videos/83/thumbs/wfrYZ4PD1D2.jpg', 'http://www.youtube.com/watch?v=V8PidNJLrek&feature=related', 0, 0, 'file'),
(11, 'Top 10 Best Web Hosting Reviews - SCAMS EXPOSED', 'youtube', 'V8PidNJLrek', 'Are "HOST REVIEW" sites honest? Are they unbiased, impartial, and factual... or are they just after your money? How does a hosting company get on the "top 10" list? \r\n\r\nAmazingly most hosting reviews websites have one thing in common: They are getting paid by hosting companies for reviews (either directly in the form of advertising or indirectly via affiliate commissions) -- making their reviews extremely biased, one-sided, and highly questionable in terms of accuracy. They all promote the same group of companies. \r\n\r\nThe reason that the same hosting companies always make it to the "top" of the hosting comparison charts is because those companies, one way or another, pay to be listed there. These hosts include Host Monster, Blue Host, Lunar Pages, IX Webhosting, InMotionHosting, StartLogic, Host Pappa, Pow Web, etc. \r\n\r\nIt''s a well-known fact web hosting companies running their affiliate programs through Commission Junction offer among the highest affiliate commissions in the hosting industry. Thus "clever" PPC (pay per click) affiliate marketers decided: why not create websites with "top web hosting companies" lists and list these companies as "top"? \r\n\r\nHosting company reviews seldom base their "rating" on their quality of service (although many claim to). Instead, most of them rate a webhost on the *size* of the affiliate commission. Those web hosts offering the highest commissions usually get the top spots -- because those hosting companies pay the most money.\r\n\r\nSo the next time you''re looking for the best web hosting company (and you undoubtedly come across a "reviews" site), STOP AND THINK: What''s their true objective? Are they providing you with impartial, unprejudiced facts? Or are they simply selling you a bill of goods, deceptively packaged in a "Top-10" list bought and paid for in the Twilight Zone? Visit HOSTING-REVIEWS-EXPOSED.COM for more information.', 83, 'user', '2010-07-01 13:15:18', '0', 1, 6, 1, 0, 211, 'ready', 'images/videos/83/thumbs/wfrYZ4PD1D2.jpg', 'http://www.youtube.com/watch?v=V8PidNJLrek&feature=related', 0, 0, 'file'),
(12, 'Top 10 Best Web Hosting Reviews - SCAMS EXPOSED', 'youtube', 'V8PidNJLrek', 'Are "HOST REVIEW" sites honest? Are they unbiased, impartial, and factual... or are they just after your money? How does a hosting company get on the "top 10" list? \r\n\r\nAmazingly most hosting reviews websites have one thing in common: They are getting paid by hosting companies for reviews (either directly in the form of advertising or indirectly via affiliate commissions) -- making their reviews extremely biased, one-sided, and highly questionable in terms of accuracy. They all promote the same group of companies. \r\n\r\nThe reason that the same hosting companies always make it to the "top" of the hosting comparison charts is because those companies, one way or another, pay to be listed there. These hosts include Host Monster, Blue Host, Lunar Pages, IX Webhosting, InMotionHosting, StartLogic, Host Pappa, Pow Web, etc. \r\n\r\nIt''s a well-known fact web hosting companies running their affiliate programs through Commission Junction offer among the highest affiliate commissions in the hosting industry. Thus "clever" PPC (pay per click) affiliate marketers decided: why not create websites with "top web hosting companies" lists and list these companies as "top"? \r\n\r\nHosting company reviews seldom base their "rating" on their quality of service (although many claim to). Instead, most of them rate a webhost on the *size* of the affiliate commission. Those web hosts offering the highest commissions usually get the top spots -- because those hosting companies pay the most money.\r\n\r\nSo the next time you''re looking for the best web hosting company (and you undoubtedly come across a "reviews" site), STOP AND THINK: What''s their true objective? Are they providing you with impartial, unprejudiced facts? Or are they simply selling you a bill of goods, deceptively packaged in a "Top-10" list bought and paid for in the Twilight Zone? Visit HOSTING-REVIEWS-EXPOSED.COM for more information.', 84, 'user', '2010-07-01 13:15:18', '0', 1, 6, 1, 0, 211, 'ready', 'images/videos/83/thumbs/wfrYZ4PD1D2.jpg', 'http://www.youtube.com/watch?v=V8PidNJLrek&feature=related', 0, 0, 'file');;

TRUNCATE TABLE `#__community_connection`;;
INSERT INTO `#__community_connection` (`connection_id`, `connect_from`, `connect_to`, `status`, `group`, `created`, `msg`) VALUES
(1, 85, 84, 1, 0, NULL, ''),
(2, 84, 82, 1, 0, NULL, ''),
(13, 79, 81, 1, 0, '2010-06-15 09:30:42', ''),
(8, 79, 80, 1, 0, '2010-06-15 09:29:15', ''),
(9, 80, 79, 1, 0, '2010-06-15 09:29:15', ''),
(11, 80, 81, 1, 0, '2010-06-15 09:30:40', ''),
(12, 81, 80, 1, 0, '2010-06-15 09:30:40', ''),
(14, 81, 79, 1, 0, '2010-06-15 09:30:42', ''),
(20, 96, 80, 1, 0, '2010-06-15 10:24:25', ''),
(22, 97, 81, 1, 0, '2010-06-15 10:25:01', ''),
(18, 79, 95, 1, 0, '2010-06-15 10:23:19', ''),
(19, 95, 79, 1, 0, '2010-06-15 10:23:19', ''),
(21, 80, 96, 1, 0, '2010-06-15 10:24:25', ''),
(23, 81, 97, 1, 0, '2010-06-15 10:25:01', ''),
(29, 82, 83, 1, 0, '2010-07-02 16:58:12', ''),
(28, 83, 82, 1, 0, '2010-07-02 16:58:12', ''),
(31, 84, 83, 1, 0, '2010-07-02 17:40:26', ''),
(32, 83, 84, 1, 0, '2010-07-02 17:40:26', '');;



