TRUNCATE TABLE `#__community_users`;;
INSERT INTO `#__community_users` (`userid`, `status`, `points`, `posted_on`, `avatar`, `thumb`, `invite`, `params`, `view`, `friendcount`) VALUES
(62, '', 12, '0000-00-00 00:00:00', 'components/com_community/assets/default.jpg', 'components/com_community/assets/default_thumb.jpg', 0, 'notifyEmailSystem=1\nprivacyProfileView=10\nprivacyPhotoView=0\nprivacyFriendsView=0\nprivacyVideoView=1\nnotifyEmailMessage=1\nnotifyEmailApps=1\nnotifyWallComment=0\n\n', 0, 0),
(83, '', 2, '0000-00-00 00:00:00', 'components/com_community/assets/group.jpg', 'components/com_community/assets/group_thumb.jpg', 0, 'notifyEmailSystem=1\nprivacyProfileView=10\nprivacyPhotoView=0\nprivacyFriendsView=0\nprivacyVideoView=1\nnotifyEmailMessage=1\nnotifyEmailApps=1\nnotifyWallComment=0\n\n', 0, 0),
(84, '', 2, '0000-00-00 00:00:00', 'components/com_community/assets/default.jpg', 'components/com_community/assets/default_thumb.jpg', 0, 'notifyEmailSystem=1\nprivacyProfileView=10\nprivacyPhotoView=0\nprivacyFriendsView=0\nprivacyVideoView=1\nnotifyEmailMessage=1\nnotifyEmailApps=1\nnotifyWallComment=0\n\n', 0, 0),
(85, '', 2, '0000-00-00 00:00:00', 'components/com_community/assets/default.jpg', 'components/com_community/assets/default_thumb.jpg', 0, 'notifyEmailSystem=1\nprivacyProfileView=10\nprivacyPhotoView=0\nprivacyFriendsView=0\nprivacyVideoView=1\nnotifyEmailMessage=1\nnotifyEmailApps=1\nnotifyWallComment=0\n\n', 0, 0),
(86, '', 3, '0000-00-00 00:00:00', 'components/com_community/assets/group.jpg', 'components/com_community/assets/group_thumb.jpg', 0, 'notifyEmailSystem=1\nprivacyProfileView=10\nprivacyPhotoView=0\nprivacyFriendsView=0\nprivacyVideoView=1\nnotifyEmailMessage=1\nnotifyEmailApps=1\nnotifyWallComment=0\n\n', 0, 0),
(87, '', 2, '0000-00-00 00:00:00', 'components/com_community/assets/default.jpg', 'components/com_community/assets/default_thumb.jpg', 0, 'notifyEmailSystem=1\nprivacyProfileView=10\nprivacyPhotoView=0\nprivacyFriendsView=0\nprivacyVideoView=1\nnotifyEmailMessage=1\nnotifyEmailApps=1\nnotifyWallComment=0\n\n', 0, 0),
(79, '', 8, '0000-00-00 00:00:00', 'components/com_community/assets/default.jpg', 'components/com_community/assets/default_thumb.jpg', 0, 'notifyEmailSystem=1\nprivacyProfileView=10\nprivacyPhotoView=0\nprivacyFriendsView=0\nprivacyVideoView=1\nnotifyEmailMessage=1\nnotifyEmailApps=1\nnotifyWallComment=0\n\n', 0, 3),
(80, '', 8, '0000-00-00 00:00:00', 'components/com_community/assets/group.jpg', 'components/com_community/assets/group_thumb.jpg', 0, 'notifyEmailSystem=1\nprivacyProfileView=10\nprivacyPhotoView=0\nprivacyFriendsView=0\nprivacyVideoView=1\nnotifyEmailMessage=1\nnotifyEmailApps=1\nnotifyWallComment=0\n\n', 3, 3),
(81, '', 8, '0000-00-00 00:00:00', 'components/com_community/assets/default.jpg', 'components/com_community/assets/default_thumb.jpg', 0, 'notifyEmailSystem=1\nprivacyProfileView=10\nprivacyPhotoView=0\nprivacyFriendsView=0\nprivacyVideoView=1\nnotifyEmailMessage=1\nnotifyEmailApps=1\nnotifyWallComment=0\n\n', 4, 3),
(82, '', 3, '0000-00-00 00:00:00', 'components/com_community/assets/default.jpg', 'components/com_community/assets/default_thumb.jpg', 0, 'notifyEmailSystem=1\nprivacyProfileView=10\nprivacyPhotoView=0\nprivacyFriendsView=0\nprivacyVideoView=1\nnotifyEmailMessage=1\nnotifyEmailApps=1\nnotifyWallComment=0\n\n', 0, 0),
(88, '', 2, '0000-00-00 00:00:00', 'components/com_community/assets/default.jpg', 'components/com_community/assets/default_thumb.jpg', 0, 'notifyEmailSystem=1\nprivacyProfileView=10\nprivacyPhotoView=0\nprivacyFriendsView=0\nprivacyVideoView=1\nnotifyEmailMessage=1\nnotifyEmailApps=1\nnotifyWallComment=0\n\n', 0, 0),
(89, '', 2, '0000-00-00 00:00:00', 'components/com_community/assets/default.jpg', 'components/com_community/assets/default_thumb.jpg', 0, 'notifyEmailSystem=1\nprivacyProfileView=10\nprivacyPhotoView=0\nprivacyFriendsView=0\nprivacyVideoView=1\nnotifyEmailMessage=1\nnotifyEmailApps=1\nnotifyWallComment=0\n\n', 0, 0),
(90, '', 2, '0000-00-00 00:00:00', 'components/com_community/assets/default.jpg', 'components/com_community/assets/default_thumb.jpg', 0, 'notifyEmailSystem=1\nprivacyProfileView=10\nprivacyPhotoView=0\nprivacyFriendsView=0\nprivacyVideoView=1\nnotifyEmailMessage=1\nnotifyEmailApps=1\nnotifyWallComment=0\n\n', 0, 0),
(96, '', 6, '0000-00-00 00:00:00', 'components/com_community/assets/default.jpg', 'components/com_community/assets/default_thumb.jpg', 0, 'notifyEmailSystem=1\nprivacyProfileView=10\nprivacyPhotoView=0\nprivacyFriendsView=0\nprivacyVideoView=1\nnotifyEmailMessage=1\nnotifyEmailApps=1\nnotifyWallComment=0\n\n', 0, 1),
(92, '', 2, '0000-00-00 00:00:00', 'components/com_community/assets/default.jpg', 'components/com_community/assets/default_thumb.jpg', 0, 'notifyEmailSystem=1\nprivacyProfileView=10\nprivacyPhotoView=0\nprivacyFriendsView=0\nprivacyVideoView=1\nnotifyEmailMessage=1\nnotifyEmailApps=1\nnotifyWallComment=0\n\n', 0, 0),
(93, '', 2, '0000-00-00 00:00:00', 'images/avatar/795ac503753aaf891e6391ad.gif', 'images/avatar/thumb_795ac503753aaf891e6391ad.gif', 0, 'notifyEmailSystem=1\nprivacyProfileView=30\nprivacyPhotoView=0\nprivacyFriendsView=0\nprivacyVideoView=1\nnotifyEmailMessage=1\nnotifyEmailApps=1\nnotifyWallComment=0\n\n', 0, 0),
(95, '', 6, '0000-00-00 00:00:00', 'components/com_community/assets/default.jpg', 'components/com_community/assets/default_thumb.jpg', 0, 'notifyEmailSystem=1\nprivacyProfileView=10\nprivacyPhotoView=0\nprivacyFriendsView=0\nprivacyVideoView=1\nnotifyEmailMessage=1\nnotifyEmailApps=1\nnotifyWallComment=0\n\n', 1, 1),
(97, '', 6, '0000-00-00 00:00:00', 'components/com_community/assets/default.jpg', 'components/com_community/assets/default_thumb.jpg', 0, 'notifyEmailSystem=1\nprivacyProfileView=10\nprivacyPhotoView=0\nprivacyFriendsView=0\nprivacyVideoView=1\nnotifyEmailMessage=1\nnotifyEmailApps=1\nnotifyWallComment=0\n\n', 0, 1);;




TRUNCATE TABLE `#__xipt_profiletypes` ;;
INSERT INTO `#__xipt_profiletypes` (`id`, `name`, `ordering`, `published`, `tip`, `privacy`, `template`, `jusertype`, `avatar`, `approve`, `allowt`, `group`, `watermark`, `params`,`watermarkparams`,`visible`) VALUES
(1, 'PROFILETYPE-1', 2, 1, '<p>PROFILETYPE-ONE-TIP</p>', 'public', 'default', 'Registered', 'components/com_community/assets/default.jpg', 0, 0, 1, '', '', 'enableWaterMark=0\nxiText=P1\nxiWidth=40\nxiHeight=40\nxiThumbWidth=20\nxiThumbHeight=20\nxiFontName=monofont\nxiFontSize=26\nxiTextColor=FFFFFF\nxiBackgroundColor=9CD052\nxiWatermarkPosition=tl\ndemo=1\n\n', 1),
(2, 'PROFILETYPE-2', 1, 1, '<p>PROFILETYPE-TWO-TIP</p>', 'friends', 'blueface', 'Editor', 'images/profiletype/avatar_2.jpg', 0, 0, 0, '', '', 'enableWaterMark=0\nxiText=P2\nxiWidth=40\nxiHeight=40\nxiThumbWidth=20\nxiThumbHeight=20\nxiFontName=monofont\nxiFontSize=26\nxiTextColor=FFFFFF\nxiBackgroundColor=9CD052\nxiWatermarkPosition=tl\ndemo=2\n\n', 1),
(3, 'PROFILETYPE-3', 3, 1, '<p>PROFILETYPE-THREE-TIP</p>', 'members', 'blackout', 'Publisher', 'components/com_community/assets/default.jpg', 0, 0, 4, '', '', 'enableWaterMark=0\nxiText=P3\nxiWidth=40\nxiHeight=40\nxiThumbWidth=20\nxiThumbHeight=20\nxiFontName=monofont\nxiFontSize=26\nxiTextColor=FFFFFF\nxiBackgroundColor=9CD052\nxiWatermarkPosition=tl\ndemo=3\n\n', 1),
(4, 'PROFILETYPE-4', 4, 0, '<p>PROFILETYPE-FOUR-TIP</p>', 'public', 'blackout', 'Registered', 'components/com_community/assets/default.jpg', 0, 0, 0, 'images/profiletype/watermark_4.png', '', 'enableWaterMark=0\nxiText=P4\nxiWidth=40\nxiHeight=40\nxiThumbWidth=20\nxiThumbHeight=20\nxiFontName=monofont\nxiFontSize=26\nxiTextColor=FFFFFF\nxiBackgroundColor=9CD052\nxiWatermarkPosition=tl\ndemo=4\n\n', 1),
(5, 'PROFILETYPE-5', 5, 1, '<p>PROFILETYPE-FIVE-TIP</p>', 'public', 'default', 'Registered', 'components/com_community/assets/default.jpg', 0, 0, 0, 'images/profiletype/watermark_5.png', '', 'enableWaterMark=0\nxiText=P\nxiWidth=40\nxiHeight=40\nxiThumbWidth=20\nxiThumbHeight=20\nxiFontName=monofont\nxiFontSize=26\nxiTextColor=FFFFFF\nxiBackgroundColor=9CD052\nxiWatermarkPosition=tl\ndemo=5\n\n', 1),
(6, 'PROFILETYPE-6', 6, 1, '<p>PROFILETYOE-SIX-TIP</p>', 'public', 'default', 'Registered', 'components/com_community/assets/default.jpg', 0, 0, 0, 'images/profiletype/watermark_6.png', '', 'enableWaterMark=0\nxiText=P\nxiWidth=40\nxiHeight=40\nxiThumbWidth=20\nxiThumbHeight=20\nxiFontName=monofont\nxiFontSize=26\nxiTextColor=FFFFFF\nxiBackgroundColor=9CD052\nxiWatermarkPosition=tl\ndemo=6\n\n', 1);;

TRUNCATE TABLE `#__xipt_aclrules`;;
INSERT INTO `#__xipt_aclrules` (`id`, `rulename`, `aclname`, `coreparams`, `aclparams`, `published`) VALUES
(10, 'access video', 'accessvideo', 'core_profiletype=3\ncore_display_message=PHA+WU9VIEFSRSBOT1QgQUxMT1dFRCBUTyBBQ0NFU1MgVEhJUyBSRVNPVVJDRTwvcD4=\nforce_to_redirect=0\ncore_redirect_url=index.php?option=com_community\n\n', 'other_profiletype=1\nacl_applicable_to_friend=0\n\n', 1),
(11, 'access video', 'accessvideo', 'core_profiletype=2\ncore_display_message=PHA+WU9VIEFSRSBOT1QgQUxMT1dFRCBUTyBBQ0NFU1MgVEhJUyBSRVNPVVJDRTwvcD4=\nforce_to_redirect=0\ncore_redirect_url=index.php?option=com_community\n\n', 'other_profiletype=3\nacl_applicable_to_friend=0\n\n', 1),
(12, 'access video', 'accessvideo', 'core_profiletype=1\ncore_display_message=PHA+WU9VIEFSRSBOT1QgQUxMT1dFRCBUTyBBQ0NFU1MgVEhJUyBSRVNPVVJDRTwvcD4=\nforce_to_redirect=0\ncore_redirect_url=index.php?option=com_community\n\n', 'other_profiletype=2\nacl_applicable_to_friend=0\n\n', 1),
(13, 'access video', 'accessvideo', 'core_profiletype=1\ncore_display_message=PHA+WU9VIEFSRSBOT1QgQUxMT1dFRCBUTyBBQ0NFU1MgVEhJUyBSRVNPVVJDRTwvcD4=\nforce_to_redirect=0\ncore_redirect_url=index.php?option=com_community\n\n', 'other_profiletype=4\nacl_applicable_to_friend=1\n\n', 1),
(14, 'access video', 'accessvideo', 'core_profiletype=2\ncore_display_message=PHA+WU9VIEFSRSBOT1QgQUxMT1dFRCBUTyBBQ0NFU1MgVEhJUyBSRVNPVVJDRTwvcD4=\nforce_to_redirect=0\ncore_redirect_url=index.php?option=com_community\n\n', 'other_profiletype=5\nacl_applicable_to_friend=1\n\n', 1),
(15, 'access video', 'accessvideo', 'core_profiletype=3\ncore_display_message=PHA+WU9VIEFSRSBOT1QgQUxMT1dFRCBUTyBBQ0NFU1MgVEhJUyBSRVNPVVJDRTwvcD4=\nforce_to_redirect=0\ncore_redirect_url=index.php?option=com_community\n\n', 'other_profiletype=6\nacl_applicable_to_friend=1\n\n', 1);;



TRUNCATE TABLE `#__community_videos`;;
INSERT INTO `#__community_videos` (`id`, `title`, `type`, `video_id`, `description`, `creator`, `creator_type`, `created`, `permissions`, `category_id`, `hits`, `published`, `featured`, `duration`, `status`, `thumb`, `path`, `groupid`, `filesize`, `storage`) VALUES
(1, 'Kites Song Fire |  Kites Fire  |  Hrithik Roshan Fire  |  Kites Song Promo  Fire  |  Fire |', 'youtube', 'PN626ZXD204', 'Kites Song Promo -  Fire  \r\nChoreographer - Flexy        Music - Rajesh Roshan\r\n\r\nKITES Releasing Worldwide on 21st May (2010)', 85, 'user', '2010-05-25 11:57:38', '0', 1, 3, 1, 0, 62, 'ready', 'images/videos/88/thumbs/BeYcKnpwhj9.jpg', 'http://www.youtube.com/watch?v=PN626ZXD204', 0, 0, 'file'),
(2, 'PHP Tutorial: Installation and The Basics', 'youtube', 'afgyNp5HueQ', 'PHP', 86, 'user', '2010-05-25 12:19:16', '0', 1, 6, 1, 0, 654, 'ready', 'images/videos/89/thumbs/RyQFKAMfQuS.jpg', 'http://www.youtube.com/watch?v=afgyNp5HueQ', 0, 0, 'file'),
(3, 'Hrithik Roshan''s Superb Dancing in Kites (2010) *HD*', 'youtube', 'luXxeIlOoKU', 'Hrithik Roshan, Dance, Kites, Hindi Movie, Watch Online, SominalTv, Kangana Ranawat, Fire, Full Song, Music Video', 87, 'user', '2010-05-25 12:28:01', '0', 1, 4, 1, 0, 189, 'ready', 'images/videos/90/thumbs/gQ1sAuG34du.jpg', 'http://www.youtube.com/watch?v=luXxeIlOoKU', 0, 0, 'file'),
(4, 'Build a Joomla Website', 'youtube', 'lGub1u8v8i8', 'http:www.buildajoomlawebsite.com\r\nIf you have ever wanted to build a Joomla website...you need to see this', 79, 'user', '2010-06-15 09:21:24', '0', 1, 0, 1, 0, 298, 'ready', 'images/videos/79/thumbs/O6iK9kZPqFt.jpg', 'http://www.youtube.com/watch?v=lGub1u8v8i8&feature=related', 0, 0, 'file'),
(5, 'Build easy websites using Joomla tutorials', 'youtube', 'fVr7huePbIA', 'Its a clip that shows you ways to build a website using joomla..a powerful open source...\r\n\r\nYou can create websites in 10 mins..that too with features and a database that supports..and gives you access to admin..enjoy!!\r\n\r\nfind more information from joomlasuccess.com', 80, 'user', '2010-06-15 09:23:09', '0', 1, 0, 1, 0, 15, 'ready', 'images/videos/80/thumbs/SsnDTqPD89x.jpg', 'http://www.youtube.com/watch?v=fVr7huePbIA&feature=related', 0, 0, 'file'),
(6, 'How to Build and Manage Your Own Website - (Joomla Editors)', 'youtube', 'ESEU8XqyrZE', 'http:www.MakeYourWebsite123.com\r\n\r\nEasily Edit, Design And Format Your Pages Using WYSIWYG Editor, Without Ever Messing With HTML And Other Programming Languages\r\nMake you own website\r\nmake a website\r\nhow to make a website\r\nhow to make your own website for free', 81, 'user', '2010-06-15 09:25:14', '0', 1, 0, 1, 0, 272, 'ready', 'images/videos/81/thumbs/rSG2g8pNIYc.jpg', 'http://www.youtube.com/watch?v=ESEU8XqyrZE&feature=related', 0, 0, 'file'),
(7, 'How to createmake your own website 4 free', 'youtube', 'qB6zTgMWcDA', 'this is how to create youre own website first: go to www.freeservers.com and then click the box with the free on the top. and then follow the steps and fill the blanks and in no time you have you''re website!\r\n\r\n AXLPOGI Productions-MADE IN PHILIPPINES', 95, 'user', '2010-06-15 10:11:53', '0', 1, 0, 1, 0, 226, 'ready', 'images/videos/95/thumbs/HW82lNd9oWo.jpg', 'http://www.youtube.com/watch?v=qB6zTgMWcDA&feature=related', 0, 0, 'file'),
(8, 'Make a free website!!', 'youtube', '8aaNngwsY3c', 'its cool free and fast!! great for gamers, for clans yada yada yada\r\nmy site: www.valenciascape.ucoz.com\r\nto register for a site:www.ucoz.com', 96, 'user', '2010-06-15 10:15:12', '0', 1, 1, 1, 0, 220, 'ready', 'images/videos/96/thumbs/BN4EaRT8955.jpg', 'http://www.youtube.com/watch?v=8aaNngwsY3c&feature=related', 0, 0, 'file'),
(9, 'Best Free Website Hosting: With FTP, PHP, and MySQL!', 'youtube', 'whPYvGuqviI', 'Free website hosting.\r\nhttp:www.podserver.info\r\nHost your own message board forum, blog, CMS, image gallery, Commerce, wiki, and more. Unlike other free hosting plans, this includes full access to FTP, PHP, MySQL, Apache and Control Panel.\r\n\r\nFree web hosting services:\r\n• 300 MB disk space\r\n• 10 GB monthly transfer\r\n• 7 MySQL databases\r\n• Free 247 tech support and instant activation\r\n• FTP, file manager, MySQL, Ion Cube, Zend Optimizer, and Apache\r\n• PHP with ''safe_mode'' off and GD enabled\r\n• Password protect directories\r\n• Control panel and Fantastico® like automatic script installer\r\n• 6 Addon domains, 6 parked domains, and 6 sub-domains\r\n• Webmail, sendmail and POP email\r\n• Quad Xeon grid servers with multiple fiber optic connections\r\n\r\nMusic: Kevin MacLeod', 97, 'user', '2010-06-15 10:20:07', '0', 1, 1, 1, 0, 32, 'ready', 'images/videos/97/thumbs/gNRmYbqgB33.jpg', 'http://www.youtube.com/watch?v=whPYvGuqviI&feature=related', 0, 0, 'file');;

TRUNCATE TABLE  `#__community_connection` ;;
INSERT INTO `#__community_connection` (`connection_id`, `connect_from`, `connect_to`, `status`, `group`, `created`, `msg`) VALUES
(1, 85, 84, 1, 0, NULL, ''),
(2, 84, 82, 1, 0, NULL, ''),
(13, 79, 81, 1, 0, '2010-06-15 09:30:42', ''),
(8, 79, 80, 1, 0, '2010-06-15 09:29:15', ''),
(9, 80, 79, 1, 0, '2010-06-15 09:29:15', ''),
(11, 80, 81, 1, 0, '2010-06-15 09:30:40', ''),
(12, 81, 80, 1, 0, '2010-06-15 09:30:40', ''),
(14, 81, 79, 1, 0, '2010-06-15 09:30:42', ''),
(20, 96, 80, 1, 0, '2010-06-15 10:24:25', ''),
(22, 97, 81, 1, 0, '2010-06-15 10:25:01', ''),
(18, 79, 95, 1, 0, '2010-06-15 10:23:19', ''),
(19, 95, 79, 1, 0, '2010-06-15 10:23:19', ''),
(21, 80, 96, 1, 0, '2010-06-15 10:24:25', ''),
(23, 81, 97, 1, 0, '2010-06-15 10:25:01', '');;
